"""describe_change

Revision ID: 1aba5c5cf770
Revises: 0002_six_digit_otp_auth
Create Date: 2026-07-19 12:49:47.503813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aba5c5cf770'
down_revision: Union[str, Sequence[str], None] = '0002_six_digit_otp_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
